name: plots # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '0.8.4' # just for humans, typically '1.2+git' or '1.3.2'
adopt-info: plots
icon: snap/gui/plots.svg
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf
plugs:
  plots:
    interface: dbus
    bus: session
    name: com.github.alexhuntley.Plots

environment:
  # WORKAROUND: Add python modules in Snap to search path
  PYTHONPATH: ${SNAP}/lib/python3.10/site-packages:${SNAP}/usr/lib/python3/dist-packages
parts:
  pygobject:
    after: [ pycairo, meson-deps ]
    source: https://gitlab.gnome.org/amolenaar/pygobject.git
    source-branch: gtk-4-10-css-provider
    plugin: meson
    meson-parameters:
      - --prefix=/usr
      - -Doptimization=3
      - -Ddebug=true
  plots:
    after: [pygobject]
    # See 'snapcraft plugins'
    plugin: python
    source: https://github.com/alexhuntley/Plots.git
    source-tag: v${SNAPCRAFT_PROJECT_VERSION}
    build-environment:
      # WORKAROUND: The python plugin is broken with gnome extension
      - PATH: ${CRAFT_PART_INSTALL}/bin:${PATH}
      - PYTHONPATH: ""
    stage:
      # WORKAROUND: Skip venv from python plugin
      - -bin/activate
      - -bin/activate.csh
      - -bin/activate.fish
      - -bin/Activate.ps1
      - -bin/python
      - -bin/python3
      - -bin/python3.10
      - -bin/pip
      - -bin/pip3
      - -pyvenv.cfg
    python-packages:
      - PyOpenGL
      - numpy
      - lark
      - PyGLM
      - freetype-py
    build-packages:
      - python3-jinja2
    override-build: |
      craftctl default
      # WORKAROUND: Use python from search path, the path detected by meson doesn't exist when running the Snap
      install -D $CRAFT_PART_SRC/res/com.github.alexhuntley.Plots.metainfo.xml -t $CRAFT_PART_INSTALL/share/metainfo/
      install -D $CRAFT_PART_SRC/help/C/* -t $CRAFT_PART_INSTALL/share/help/C/plots/ 
      install -D $CRAFT_PART_SRC/help/de/* -t $CRAFT_PART_INSTALL/share/help/de/plots/
      install -D $CRAFT_PART_SRC/help/es/* -t $CRAFT_PART_INSTALL/share/help/es/plots/ 
      install -D $CRAFT_PART_SRC/help/fa/* -t $CRAFT_PART_INSTALL/share/help/fa/plots/ 
      install -D $CRAFT_PART_SRC/help/fr/* -t $CRAFT_PART_INSTALL/share/help/fr/plots/ 
      install -D $CRAFT_PART_SRC/help/hr/* -t $CRAFT_PART_INSTALL/share/help/hr/plots/ 
      install -D $CRAFT_PART_SRC/help/hu/* -t $CRAFT_PART_INSTALL/share/help/hu/plots/ 
      install -D $CRAFT_PART_SRC/help/it/* -t $CRAFT_PART_INSTALL/share/help/it/plots/ 
      install -D $CRAFT_PART_SRC/help/nb_NO/* -t $CRAFT_PART_INSTALL/share/help/nb_NO/plots/ 
      install -D $CRAFT_PART_SRC/help/nl/* -t $CRAFT_PART_INSTALL/share/help/nl/plots/ 
      install -D $CRAFT_PART_SRC/help/pt_BR/* -t $CRAFT_PART_INSTALL/share/help/pt_BR/plots/ 
      install -D $CRAFT_PART_SRC/help/zh_Hans/* -t $CRAFT_PART_INSTALL/share/help/zh_Hans/plots/ 
    parse-info: [share/metainfo/com.github.alexhuntley.Plots.metainfo.xml]
apps:
  plots:
    command: bin/plots
    extensions: [gnome]
    common-id: com.github.alexhuntley.Plots
    plugs:
      - home
